### ISSUE TITLE
Non-recoverable error when deleting/exiting mini compact processor

### ISSUE THREAD

**Issue by liminal** [kmecseki/Fluid-level-indicator#3]
This might be the other mods fault but if I delete or even just enter/exit a mini compact processor from the [Compakt Circuits](https://mods.factorio.com/mod/compaktcircuit) mod this Non-recoverable error happens every time. I'm assuming it's a consequence of the Compakt Circuits mod deleting a surface?

> The mod Fluid Level Indicator (0.7.3) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event Fluid-level-indicator::on_pre_surface_deleted (ID 65)
> __Fluid-level-indicator__/control.lua:36: attempt to index global 'surface' (a nil value)
> stack traceback:
> 	__Fluid-level-indicator__/control.lua:36: in function <__Fluid-level-indicator__/control.lua:35>

**Comment by kmecseki** [comment]
Thanks for letting me know, I am looking into this

**Comment by kmecseki** [comment]
The bug was in indeed my mod. ;)
I believe it is fixed now, please let me know if you still have this problem.
