### ISSUE TITLE
The mod does not work in orbit (space platform)

### ISSUE THREAD

**Issue by eugenikus8** [kmecseki/Fluid-level-indicator#9]
Indicators do not work in space if they are not built by the player.

**Comment by kmecseki** [comment]
Indeed.. thanks for letting me know! I have now added the support for them (version 0.9.5).

**Comment by eugenikus8** [comment]
Thanks for the quick fix.

**Comment by kmecseki** [comment]
You are very welcome, I should have already done this :)
